In [14]:
from e3nn.o3 import spherical_harmonics as sh
import torch
import math

In [36]:
vij = torch.tensor([[1.0,2,3],[2,1,4]])
Dij = torch.linalg.norm(vij, dim=1, keepdim=True)
pij = vij / Dij
pij

tensor([[0.2673, 0.5345, 0.8018],
        [0.4364, 0.2182, 0.8729]])

In [38]:
_sqrt3 = math.sqrt(3.0)
_sqrt3half = 0.5 * _sqrt3
p = torch.stack(
    [
        _sqrt3 * pij[:, 0] * pij[:, 1],  # xy
        _sqrt3 * pij[:, 0] * pij[:, 2],  # xz
        _sqrt3 * pij[:, 1] * pij[:, 2],  # yz
        0.5 * (3 * pij[:, 2] * pij[:, 2] - 1.0),  # z2
        _sqrt3half * (pij[:, 0] * pij[:, 0] - pij[:, 1] * pij[:, 1]),  # x2-y2
    ],
    dim=-1,
)
p

tensor([[ 0.2474,  0.3712,  0.7423,  0.4643, -0.1856],
        [ 0.1650,  0.6598,  0.3299,  0.6429,  0.1237]])

In [62]:

sh(2, pij[:, [1,2,0]], normalize=True, normalization="norm")[:, [0,3,1,2,4]]

tensor([[ 0.2474,  0.3712,  0.7423,  0.4643, -0.1856],
        [ 0.1650,  0.6598,  0.3299,  0.6429,  0.1237]])